Algoritmo "ex15"
// faca um programa que leia um numero inteiro
//e moste o seu antecessor e seu sucessor
Var
numero : inteiro
antecessor : inteiro
sucessor : inteiro

Inicio
 escreva ("Digite o numero: ")
 leia (numero)
 
 antecessor <- numero - 1
 sucessor <- numero + 1
 
 escreval("O numero digitado foi ", numero)
 escreval ("O seu antecesor é: ", antecessor)
 escreva ("O seu sucessor é: ", sucessor)
 

Fimalgoritmo