Algoritmo "ex16"
// 16 - Faça um algoritmo que leia um
//número real e mostre na tela
//o seu dobro e a sua terça parte.

Var
numero : real
dobro : real
tercaParte : real

Inicio
 escreva ("Digite o numero: ")
 leia (numero)
 
 dobro <- numero *2
 tercaParte <- numero /3
 
 escreval ("O numero digitado foi ", numero)
 escreval ("O seu dobro é: ", dobro)
 escreva ("A terca parte é: ", tercaParte)
 

Fimalgoritmo