Algoritmo "ex19"
// // 19 - Faça um algoritmo que leia a
//altura e largura de uma parede.
//Mostre quantos metros quadrados a parede tem.
Var
largura, altura, resul : real


Inicio

//Algoritmo do aluno Gustavo Ferraz
escreva ("Qual a altura da parede em metros? ")
leia (altura)
escreva ("Qual a largura da parede em metros? ")
leia (largura)


resul<-altura*largura
escreva ("o tamanho da parede em metros quadrados é: ", resul)
Fimalgoritmo