Algoritmo "Ex_10"
// Faca um algoritmo que recebe 3 numeros
// e multiplique o produto desses numeros

Var
num1, num2, num3 : real
produto : real
Inicio
escreva("digite o primeiro numero do produto: ")
leia(num1)
escreva("digite o segundo numero do produto: ")
leia(num2)
 escreva("digite o terceiro numero do produto: ")
leia(num3)

produto <- num1*num2*num3

escreva ("A multiplicacao dos produtos sao :", produto)


Fimalgoritmo