algoritmo "Ex2"
var
    num1: real
    num2: real
    num3: real
    num4: real
    num5: real
inicio
    escreva("Digite o primeiro numero: ")
    leia(num1)
    escreva("Digite o segundo numero: ")
    leia(num2)
    escreva("Digite o terceiro numero: ")
    leia(num3)
    escreva("Digite o quarto numero: ")
    leia(num4)
    escreva("Digite o quinto numero: ")
    leia(num5)
    escreva("Os numeros digitados foram: ", num1, num2, num3, num4, num5)

fimalgoritmo