Algoritmo "27"
//27 - Escreva um algoritmo que receba
// dois números inteiros e determine
// se eles são iguais ou diferentes.

Var
   num1, num2 : inteiro

Inicio
   escreva ("Digite o primeiro numero: ")
   leia (num1)
   escreva ("Digite segundo numero: ")
   leia (num2)
   se num1 <> num2 entao
      escreva ( " Os numeros sao diferentes")
   senao
      escreva ( "Os numeros sao iguais")
   fimse

Fimalgoritmo