Algoritmo "exercicio21"
// 23 - Faça um programa que leia um número
//inteiro e verifique se ele é par.
//Exiba o resto da divisão do número por 2.
//(Obs: Não usar a função "Se").

Var
numero, resto: inteiro

Inicio
escreva ("Digite o numero para verifica se ele é par ou impar: ")
leia (numero)

resto <- numero mod 2

escreva("Caso o resto seja '0' é par, se o numero
 for '1' e impar : ",resto)
Fimalgoritmo


